#!/bin/bash

test -d build || mkdir build
rm -fr build/*
cp -r src/* build/
find build -type f | while IFS=$'\n' read f; do
    if test -f .config; then
        cat .config | while IFS=$'\n' read line; do
            key=$(sed 's/^\([^= \t]\+\)[ \t]*=.*$/\1/' <<< "$line")
            value=$(sed 's/^[^=]*[ ]*=\([^ \t]\+\).*$/\1/' <<< "$line")
            key=${key//\//\\/}
            value=${value//\//\\/}
            #echo "key: $key, value: $value"
            sed -i "s/$key/$value/g" "$f"
        done
    fi
done
