#!/bin/bash

# Use temporary folder to store archive files before packing.
tmpdir=$(mktemp -d)

# Pack challenge. Function argument is path to challenge folder.
pack_challenge()
{
    session="$1"
    if test -d sol; then
        echo "Packing solution for $session ..."
        cp -r public "$tmpdir"/"$session"-sol
        tar -C "$tmpdir" -cf "$session"-sol.tar "$session"-sol
    fi
}

pack_challenge "08-system-isolation"
rm -fr "$tmpdir"
